# Generated by Django 2.2.6 on 2019-11-03 11:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post_head', models.CharField(max_length=70)),
                ('post_text', models.CharField(max_length=255)),
                ('publication_date', models.DateField(verbose_name='Date published')),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer_text', models.CharField(max_length=70)),
                ('id_post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lab4.Post')),
            ],
        ),
    ]
