# Generated by Django 2.2.6 on 2019-12-20 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lab4', '0002_comment_rating'),
    ]

    operations = [
        migrations.CreateModel(
            name='TopicStarter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('login', models.CharField(max_length=15)),
                ('password', models.CharField(max_length=15)),
                ('email', models.CharField(max_length=15)),
                ('name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='UserModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('age', models.IntegerField(max_length=6)),
                ('email', models.CharField(max_length=30)),
            ],
        ),
    ]
