# Generated by Django 2.2.6 on 2019-12-20 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lab4', '0003_topicstarter_usermodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='topicstarter',
            name='idu',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='usermodel',
            name='age',
            field=models.IntegerField(default=0),
        ),
    ]
